### ISSUE TITLE
Access denied for jobs' Published Results in examples page

### ISSUE THREAD

**Issue by Aknilam** [boalang/drupal#1]
Almost all jobs on Examples page http://boa.cs.iastate.edu/examples/ have private jobs assigned.

**Comment by psybers** [comment]
This isn't exactly the right place for notifying us about that.  This project is just about the Drupal plugin for Boa (any user starting with /boa/), not remainder of the website.

But thanks for the heads up!  It appears those jobs were marked as deleted at some point.  I'll go undelete them.

**Comment by Aknilam** [comment]
Thanks for quick fix!
Due to https://github.com/boalang/drupal/blob/master/examples.inc I thought it should be here.
